### ISSUE TITLE
不可以用了  能更新下吗

### ISSUE THREAD

**Issue by papa-cmd** [qinjintian/superchutou#1]
不可以用了  能更新下吗

**Comment by chenjinhu** [comment]
修改下登录方式就好了。 请别做伸手党

**Comment by qinjintian** [comment]
> 

官方已经取消了通过账号+密码方式登陆，只允许微信扫描或手机验证码登陆，最近比较忙没时间调整

**Comment by qinjintian** [comment]
一直没空维护，今天已经抽空加上【手机号+验证码】登录方式，可下载最新的可执行文件，运行后根据提示操作
