### ISSUE TITLE
不能用的看这里

### ISSUE THREAD

**Issue by chenjinhu** [qinjintian/superchutou#2]
估计是因为登录加了阿里滑块的原因, 懂golang的同学可以修改一下，把登录改为手动录入Cookie的方式即可.

我用Python实现了一个
![image](https://user-images.githubusercontent.com/33171100/205609407-911c6326-7ad3-4daa-ad4b-e488762ebe2c.png)

**Comment by papa-cmd** [comment]
源码有吗

**Comment by qinjintian** [comment]
一直没空维护，今天已经抽空加上【手机号+验证码】登录方式

**Comment by qinjintian** [comment]
可以下载最新的可执行文件，根据终端提示操作即可

**Comment by chenjinhu** [comment]
可以的.666
